name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Cython
      run: |
        pip install "cython<3.0"

    - name: Install Buildozer
      run: |
        pip install buildozer

    # УСТАНАВЛИВАЕМ Android SDK (включая aidl)
    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk unzip
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        mkdir -p $HOME/android/cmdline-tools
        unzip -q cmdline-tools.zip -d $HOME/android/cmdline-tools
        mv $HOME/android/cmdline-tools/cmdline-tools $HOME/android/cmdline-tools/latest
        echo "y" | $HOME/android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android/sdk "platform-tools" "platforms;android-35" "build-tools;35.0.0"

    # ДОБАВЛЯЕМ Android SDK в PATH
    - name: Set Android environment
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/android/sdk" >> $GITHUB_ENV
        echo "$HOME/android/sdk/platform-tools" >> $GITHUB_PATH
        echo "$HOME/android/cmdline-tools/latest/bin" >> $GITHUB_PATH

    # СБОРКА APK
    - name: Build APK
      run: |
        buildozer -v android debug

    # ЗАГРУЗКА APK
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MAX.apk
        path: bin/*.apk
